### ISSUE TITLE
Use another job-store?

### ISSUE THREAD

**Issue by 0xbaadf00d** [svenkubiak/ninja-quartz#2]
Hi,

Is it possible to use another job-store than "RAMJobStore" to enable persistence and enable clustering  to use Quartz between multiple instance of my Ninja 4 web project ?

**Comment by svenkubiak** [comment]
This is obsolet with your pull-request, isn't it? 
https://github.com/svenkubiak/ninja-quartz/pull/4

**Comment by 0xbaadf00d** [comment]
Yes.

**Comment by svenkubiak** [comment]
Ok, the I'll close this one.
